management:
  endpoints:
    web:
      exposure:
        include: "health,info,busrefresh"
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        springCloudBusOutput:
          destination: springCloudBus
        springCloudBusInput:
          destination: springCloudBus
        springCloudBus:
          content-type: application/json
    bus:
      enabled: true

---
spring:
  config:
    import: "optional:configserver:http://localhost:8888"

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.kafka: DEBUG

