management:
  endpoints:
    web:
      exposure:
        include: "health,info,busrefresh"
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        springCloudBusOutput:
          destination: springCloudBus
        springCloudBusInput:
          destination: springCloudBus
        springCloudBus:
          content-type: application/json
    bus:
      enabled: true

---
spring:
  config:
    import: "optional:configserver:http://localhost:8888"

---
#minio
minio:
  endpoint: http://localhost:9000
  accessKey: minio
  secretKey: minio123
  region: eu-west-1
  bucket: spring-cloud-config

app:
  config-file-name: config-file.json

spring:
  servlet:
    multipart:
      max-file-size: 10MB # Set maximum file size
      max-request-size: 12MB # Set maximum request size